name: 编译

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 编译
        run: cargo build --release
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/release/rsnano.exe

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: 编译项目
        run: cargo build --release
      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: target/release/rsnano
